spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wode?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  instance:
    prefer-ip-address: true   #以IP地址注册到服务中心
  client:
    service-url:
      defaultZone: http://139.155.87.225:8080/EurekaServer/eureka/
mybatis:
  mapper-locations: classpath*:/mapper/*.xml